2011-12-11 17:35:02.781 GMT Thread[Thread-0,5,main] Cleanup action starting
java.sql.SQLException: 数据库“C:\Documents and Settings\Administrator/javaxyq/xyqdb”未找到。
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at com.javaxyq.util.DBToolkit.prepareDatabase(DBToolkit.java:58)
	at com.javaxyq.core.BaseApplication$1.run(BaseApplication.java:70)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.sql.SQLException: 数据库“C:\Documents and Settings\Administrator/javaxyq/xyqdb”未找到。
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 16 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: 数据库“C:\Documents and Settings\Administrator/javaxyq/xyqdb”未找到。
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at com.javaxyq.util.DBToolkit.prepareDatabase(DBToolkit.java:58)
	at com.javaxyq.core.BaseApplication$1.run(BaseApplication.java:70)
	at java.lang.Thread.run(Thread.java:619)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
2011-12-11 17:35:02.906 GMT???
?≠??ú?????????∞????∫ì????Ω? C:\Documents and Settings\Administrator\javaxyq\xyqdb  ‰∏≠???
Derby VThe Apache Software Foundation - Apache Derby - 10.5.3.0 - (802917) ???‰?? a816c00e-0134-2e31-2fb2-000000c92568

数据库类装入器已启动 － derby.database.classpath=“”
